// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example .proto

public final class Example {
  private Example() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface YourMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:YourMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string mediaPid = 1;</code>
     * @return The mediaPid.
     */
    java.lang.String getMediaPid();
    /**
     * <code>string mediaPid = 1;</code>
     * @return The bytes for mediaPid.
     */
    com.google.protobuf.ByteString
        getMediaPidBytes();

    /**
     * <code>int32 dspId = 2;</code>
     * @return The dspId.
     */
    int getDspId();

    /**
     * <code>string mediaName = 3;</code>
     * @return The mediaName.
     */
    java.lang.String getMediaName();
    /**
     * <code>string mediaName = 3;</code>
     * @return The bytes for mediaName.
     */
    com.google.protobuf.ByteString
        getMediaNameBytes();
  }
  /**
   * Protobuf type {@code YourMessage}
   */
  public static final class YourMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:YourMessage)
      YourMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use YourMessage.newBuilder() to construct.
    private YourMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private YourMessage() {
      mediaPid_ = "";
      mediaName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new YourMessage();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Example.internal_static_YourMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Example.internal_static_YourMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Example.YourMessage.class, Example.YourMessage.Builder.class);
    }

    public static final int MEDIAPID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object mediaPid_ = "";
    /**
     * <code>string mediaPid = 1;</code>
     * @return The mediaPid.
     */
    @java.lang.Override
    public java.lang.String getMediaPid() {
      java.lang.Object ref = mediaPid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mediaPid_ = s;
        return s;
      }
    }
    /**
     * <code>string mediaPid = 1;</code>
     * @return The bytes for mediaPid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMediaPidBytes() {
      java.lang.Object ref = mediaPid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mediaPid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DSPID_FIELD_NUMBER = 2;
    private int dspId_ = 0;
    /**
     * <code>int32 dspId = 2;</code>
     * @return The dspId.
     */
    @java.lang.Override
    public int getDspId() {
      return dspId_;
    }

    public static final int MEDIANAME_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object mediaName_ = "";
    /**
     * <code>string mediaName = 3;</code>
     * @return The mediaName.
     */
    @java.lang.Override
    public java.lang.String getMediaName() {
      java.lang.Object ref = mediaName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mediaName_ = s;
        return s;
      }
    }
    /**
     * <code>string mediaName = 3;</code>
     * @return The bytes for mediaName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMediaNameBytes() {
      java.lang.Object ref = mediaName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mediaName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mediaPid_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, mediaPid_);
      }
      if (dspId_ != 0) {
        output.writeInt32(2, dspId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mediaName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, mediaName_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mediaPid_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, mediaPid_);
      }
      if (dspId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, dspId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mediaName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, mediaName_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Example.YourMessage)) {
        return super.equals(obj);
      }
      Example.YourMessage other = (Example.YourMessage) obj;

      if (!getMediaPid()
          .equals(other.getMediaPid())) return false;
      if (getDspId()
          != other.getDspId()) return false;
      if (!getMediaName()
          .equals(other.getMediaName())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MEDIAPID_FIELD_NUMBER;
      hash = (53 * hash) + getMediaPid().hashCode();
      hash = (37 * hash) + DSPID_FIELD_NUMBER;
      hash = (53 * hash) + getDspId();
      hash = (37 * hash) + MEDIANAME_FIELD_NUMBER;
      hash = (53 * hash) + getMediaName().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Example.YourMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Example.YourMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Example.YourMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Example.YourMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Example.YourMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Example.YourMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Example.YourMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Example.YourMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Example.YourMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Example.YourMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Example.YourMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Example.YourMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Example.YourMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code YourMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:YourMessage)
        Example.YourMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Example.internal_static_YourMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Example.internal_static_YourMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Example.YourMessage.class, Example.YourMessage.Builder.class);
      }

      // Construct using Example.YourMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        mediaPid_ = "";
        dspId_ = 0;
        mediaName_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Example.internal_static_YourMessage_descriptor;
      }

      @java.lang.Override
      public Example.YourMessage getDefaultInstanceForType() {
        return Example.YourMessage.getDefaultInstance();
      }

      @java.lang.Override
      public Example.YourMessage build() {
        Example.YourMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Example.YourMessage buildPartial() {
        Example.YourMessage result = new Example.YourMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(Example.YourMessage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.mediaPid_ = mediaPid_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.dspId_ = dspId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.mediaName_ = mediaName_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Example.YourMessage) {
          return mergeFrom((Example.YourMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Example.YourMessage other) {
        if (other == Example.YourMessage.getDefaultInstance()) return this;
        if (!other.getMediaPid().isEmpty()) {
          mediaPid_ = other.mediaPid_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getDspId() != 0) {
          setDspId(other.getDspId());
        }
        if (!other.getMediaName().isEmpty()) {
          mediaName_ = other.mediaName_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                mediaPid_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                dspId_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                mediaName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object mediaPid_ = "";
      /**
       * <code>string mediaPid = 1;</code>
       * @return The mediaPid.
       */
      public java.lang.String getMediaPid() {
        java.lang.Object ref = mediaPid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mediaPid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string mediaPid = 1;</code>
       * @return The bytes for mediaPid.
       */
      public com.google.protobuf.ByteString
          getMediaPidBytes() {
        java.lang.Object ref = mediaPid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mediaPid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string mediaPid = 1;</code>
       * @param value The mediaPid to set.
       * @return This builder for chaining.
       */
      public Builder setMediaPid(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        mediaPid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string mediaPid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMediaPid() {
        mediaPid_ = getDefaultInstance().getMediaPid();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string mediaPid = 1;</code>
       * @param value The bytes for mediaPid to set.
       * @return This builder for chaining.
       */
      public Builder setMediaPidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        mediaPid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int dspId_ ;
      /**
       * <code>int32 dspId = 2;</code>
       * @return The dspId.
       */
      @java.lang.Override
      public int getDspId() {
        return dspId_;
      }
      /**
       * <code>int32 dspId = 2;</code>
       * @param value The dspId to set.
       * @return This builder for chaining.
       */
      public Builder setDspId(int value) {

        dspId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 dspId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDspId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        dspId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object mediaName_ = "";
      /**
       * <code>string mediaName = 3;</code>
       * @return The mediaName.
       */
      public java.lang.String getMediaName() {
        java.lang.Object ref = mediaName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mediaName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string mediaName = 3;</code>
       * @return The bytes for mediaName.
       */
      public com.google.protobuf.ByteString
          getMediaNameBytes() {
        java.lang.Object ref = mediaName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mediaName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string mediaName = 3;</code>
       * @param value The mediaName to set.
       * @return This builder for chaining.
       */
      public Builder setMediaName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        mediaName_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string mediaName = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMediaName() {
        mediaName_ = getDefaultInstance().getMediaName();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string mediaName = 3;</code>
       * @param value The bytes for mediaName to set.
       * @return This builder for chaining.
       */
      public Builder setMediaNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        mediaName_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:YourMessage)
    }

    // @@protoc_insertion_point(class_scope:YourMessage)
    private static final Example.YourMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Example.YourMessage();
    }

    public static Example.YourMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<YourMessage>
        PARSER = new com.google.protobuf.AbstractParser<YourMessage>() {
      @java.lang.Override
      public YourMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<YourMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<YourMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Example.YourMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_YourMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_YourMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016example .proto\"A\n\013YourMessage\022\020\n\010media" +
      "Pid\030\001 \001(\t\022\r\n\005dspId\030\002 \001(\005\022\021\n\tmediaName\030\003 " +
      "\001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_YourMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_YourMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_YourMessage_descriptor,
        new java.lang.String[] { "MediaPid", "DspId", "MediaName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
